import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, ClerkLoaded } from "@clerk/nextjs";
import Header from "./components/header";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LingoBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ClerkLoaded>
          <Header />
          <main className="container">
            <div className="w-full flex item-start justify-center min-h-screen">
              <div className="main-page">{children}</div>
            </div>
          </main>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}