import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, ClerkLoaded } from "@clerk/nextjs";
import Header from "./components/header";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LingoBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider afterSignUpUrl="/home-page">
      <html lang="en">
        <head>
          <meta charSet="utf-8"></meta>
        </head>
        <body className={`${inter.className} flex flex-col min-h-screen`}>
          <ClerkLoaded>
            <Header />
            <main className="main-page flex-grow justify-center items-center flex flex-col">{children}
            </main>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}